apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-exchange-service
  template:
    metadata:
      labels:
        app: currency-exchange-service
    spec:
      containers:
      - name: currency-exchange-service
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/currency-exchange-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          ---------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: currency-exchange-service
