apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: <AWS_ECR_URI>:latest
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
