name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Target environment (dev, qa, prod)"
      image_tag:
        required: true
        type: string
        description: "Docker image tag to deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ inputs.environment }} \
          currency-exchange-container=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/currency-exchange:${{ inputs.image_tag }}
          kubectl rollout status deployment/${{ inputs.environment }}
