name: Main CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build_and_scan:
    uses: ./.github/workflows/build_and_scan.yml
    with:
      branch: ${{ github.ref_name }}

  deploy:
    if: github.ref_name == 'dev' || github.ref_name == 'qa' || github.ref_name == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref_name }}
      image_tag: ${{ github.sha }}

  notify:
    needs: [build_and_scan, deploy]
    uses: ./.github/workflows/notify.yml
    with:
      status: ${{ job.status }}
      environment: ${{ github.ref_name }}
