name: EKS Deployment Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - main
jobs:
  build_and_scan:
    name: Build Docker Image and Run Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/currency-exchange-sample-service:${{ github.sha }} .

      # Authenticate Docker to GitHub Container Registry
      - name: Authenticate Docker to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.tar.gz | tar -xzv -C /usr/local/bin

      # Run Trivy Scan with retry mechanism
      - name: Run Trivy Scan on Docker Image
        run: |
          for i in {1..5}; do
            trivy image ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/currency-exchange-sample-service:${{ github.sha }}
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Retrying Trivy scan... attempt $i"
            sleep $((i * 10))  # Exponential backoff (10, 20, 30 seconds)
          done

      - name: Warn on Critical Vulnerabilities (Don't Fail)
        run: |
          if grep -q "CRITICAL" trivy-report.json; then
            echo "Warning: Critical vulnerabilities found, but continuing pipeline."
            cat trivy-report.json  # Optionally, print the full report
          fi

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/currency-exchange-sample-service:${{ github.sha }}
